convert to typescript
lunchboxer/graphql-subscriptions-client pull request #7
Opened 2020-09-30 08:05 UTC by OmgImAlexis

Converts the whole lib to use typescript it's a little more of a change than https://github.com/lunchboxer/graphql-subscriptions-client/pull/6 but it should make it easier to keep the types up to date.

To build the js files just run `npm run build`.

2020-09-30 09:25 UTC, tom-fletcher commented
Nice, I had thought about doing this but didn't have the time, so I am definitely behind this PR. :clap:

I agree, this is better overall to stop the possibility of type definition drifting in the future. I'm going to close #6 in favour of this.

2020-10-02 03:38 UTC, tom-fletcher requested changes
See change in package.json

2020-10-02 03:38 UTC, tom-fletcher commented on package.json
> +  "main": "dist/index.js",
Could you add a module property pointing to the esm files? For me, the big advantage of this library is that it works with native ES module build tools, which needs to know about these.

```suggestion
  "module": "dist/esm//index.js",
  "main": "dist/index.js",
```

2020-10-02 04:07 UTC, OmgImAlexis commented
I knew I had missed something. How's that?

2020-10-21 05:18 UTC, tom-fletcher commented
@lunchboxer is it possible to have this merged and released?

2020-10-21 06:02 UTC, lunchboxer approved these changes
Looks good

2020-10-21 06:02 UTC, merged